name: Essentials
version: 1.0
main: essentials.Essentials
authors: [Scalding]
description: Custom Essentials For Mage's RolePlay
commands:
  feed:
    description: Refils your's or another's hunger bar.
    usage: /feed <player>
    aliases: [fed, eat]
  heal:
    description: Heals your's or another's health bar, removes their potions effects, and fills hunger.
    usage: /heal <player>
  lightning:
    description: Contacts thor to shine a mighty lightning strike at the location you are looking.
    usage: /lightning <distance>
    aliases: [thor, strike]
  help:
    description: Searches through all the lands for all the commands on your server.
    usage: /help
  fly:
    description: Contacts the airplanes to give the ability of flight.
    usage: /fly <player>
  warp:
    description: Flies you through the sky to a specific location.
    usage: /warp <warp>
  setwarp:
    description: Creates a warp.
    usage: /setwarp <warp>
  delwarp:
    description: Deletes a warp.
    usage: /delwarp <warp>
